[profile.default]
src = "src"
out = "out"
libs = ["lib"]

solc = "0.8.24"
optimizer = true
gas_report = ["*"]

[fmt]
line_length = 80
tab_width = 4
bracket_spacing = false
int_types = "long"
func_attrs_with_params_multiline = true
quote_style = "double"
number_underscore = "preserve"